### ISSUE TITLE
Authorblock not compiling

### ISSUE THREAD

**Issue by tubia** [msprev/dot-panzer#2]
Hi,
I'm trying to use the dotfiles for panzer from this repo: this is useful to understand the panzer styles structure.  
Actually, I'm not able to print `{\authorblock}`, I'm using the article.latex template to print a .pdf.  
This is a part of my styles.yaml file:

```
########################################################################
#                               Article                                #
########################################################################

Articolo:
    all:
        metadata:
            title: "Untitled"
            author:
                - name: "No author"
                  affiliation: "No affiliation"
                  email: "no@email"
            published: "*Draft only. Please do not cite without permission.*"
            doi: false
    latex:
        template: article.latex
        metadata:
            fontsize: 12pt
            geometry: margin=1in
            papersize: a4paper
            lang: it-IT
            language: it-IT
            locale: it-IT
        commandline:
            latex-engine: "`xelatex`"
    pdf:
        template: article.latex
        metadata:
            fontsize: 12pt
            bibliography: FILE
            csl: FILE
            geometry: margin=1in
            lang: it-IT
```

It also doesn't print the `title`.
Hints?

Thank you!
