### ISSUE TITLE
How to specify pandoc markdown extensions and variables?

### ISSUE THREAD

**Issue by jgclark** [msprev/dot-panzer#9]
I'm just trying to get going with panzer, and am gradually working out how to port my complex workflow script to panzer. I've figured out (just) how to get basic markdown —> PDF working OK. 

My previous script (ignoring filters and templates which I've not tried to get working yet) had at its core: `pandoc --from=markdown+smart+blank_before_header+escaped_line_breaks+fenced_code_blocks+line_blocks+definition_lists+startnum+inline_notes+mmd_title_block+lists_without_preceding_blankline+yaml_metadata_block+pipe_tables+table_captions -V documentclass:scrartcl -V font size:16 -V papersize:a4paper  -o talk.pdf talk.md 2>> talk.log`. I see from the documentation that I can't set `commandline` options `from` or `variable`.

What ways can I work around this to specify the many markdown options? I've tried adding 
 ```
Sermon:
   parent:
     - Base
   latex:
     metadata:
       documentclass: "`scrartcl`"
       fontsize: "`16pt`"
       compact-headings: true
       include-in-header: "`jgc-sermon1up.sty`"
```

to my new 'Sermon' style definition, but none of these appear to be noticed or acted upon. The log file gives no hint that these are seen either. Help!

(PS, as this is a help request, not an issue per se, please tell me if there's a better way to ask for help. Thanks!)

**Comment by msprev** [comment]
How about trying this:

```
Sermon:
  parent:
    - Base
  latex:
    metadata:
      documentclass: "scrartcl"
      fontsize: "16pt"
      compact-headings: true
    commandline:
      include-in-header: "`jgc-sermon1up.sty`"
```

**Comment by jgclark** [comment]
Thanks for your prompt reply. I've tried that and no change. I've tried moving this into a `styledef` section in the .md file, but no change in output either, though at least the debug.log picked up that the local styledef was overriding the global definition. So I'm stuck again. The 16pt settings turns up in debug.json, but not debug.log. Is that expected?

There are (at least) two things I'm not understanding from the documentation:

1. when I need to put double quotes around option values, and when I don't. There are examples both ways for "fontsize: 12pt" for example. 
2. knowing where I do/don't need to put a dash before an option; again it's done both ways for `commandline` settings.

I really want to get this to work! Thanks.

**Comment by msprev** [comment]
1. The double quotes are needed when you are passing raw text that you don't want to be parsed as markdown (e.g. filenames with underscores in them). This is a feature of pandoc and is described in the panzer documentation.
2. Dashes before field names as the yaml syntax for list items. This is when the commandline option can take a list of values.

How about you try this as `test.md`...

```
---
style: Sermon
styledef:
  Sermon:
    parent: Base
    latex:
      metadata:
        documentclass: scrartcl
        fontsize: 16pt
        compact-headings: true
      commandline:
        include-in-header: "`jgc-sermon1up.sty`"
...

hello world
```

and run `pandoc test.md -o test.tex`

**Comment by jgclark** [comment]
Great, that's helped me see what the issue was. I'm now using `panzer test.md -o test.tex` and the .tex output compiles to what I was hoping for in TeXworks. I was using `… -o test.pdf` following your note in [the readme here](https://github.com/msprev/dot-panzer/blob/master/readme.md) here that straight to .pdf is possible. Could you expand on the note there to explain when to use one or the other? And why some aspect of the direct-to-PDF ignores aspects of the panzer settings? Part of the reason I wound up with pandoc is that it abstracted away much of the detail of TeX/LaTeX from me (though I've since needed to dig into detail for styling), as I found the whole choice of (La)TeX processors rather confusing.  

I see from digging into latexmk.py that you use pdflatex, so I'll try that.

But back to one of my earlier questions: my original pandoc command started
`pandoc --from=markdown+smart+blank_before_header+escaped_line_breaks+fenced_code_blocks+line_blocks+definition_lists+startnum+inline_notes+mmd_title_block+lists_without_preceding_blankline+yaml_metadata_block+pipe_tables+table_captions …`
Is there a way of specifying the `+smart` smart typography (for example) through panzer? Or do I need to submit a feature request to have a new way of passing these through?

**Comment by msprev** [comment]
Customising output direct to PDF should work too, but you would need to prefix the style definition with the pdf writer (i.e. 'pdf:' rather than 'latex:'). I'd advise to use the latex writer though as it gives more flexibility.

You can use the `--from=markdown+xxxx` argument with panzer on the command line when you invoke it just as with pandoc. (I'm not sure why you need all these options though as most are pandoc defaults anyway).

**Comment by jgclark** [comment]
Thanks for your patience.

FYI I've now tried the pdf: style definition, but I can't get that to work either.
Using a pandoc comment ("To create a pdf using pandoc, use -t latex|beamer|context|ms|html5 and specify an output file with .pdf extension (-o filename.pdf)"), I tried `panzer talk-test.md -t latex -o talk-test.pdf` but that gave error `pdflatex not found. Please select a different --pdf-engine or install pidflatex`. I have pdflatex installed, and so I then include it in the `base` style a `commandline` option `pdf-engine: "`/usr/local/texlive/2016/bin/x86_64-darwin/pdflatex`"`. But then I get the error:
```
         ----- pandoc write -----
         pandoc writing with options:
           --standalone --pdf-engine=/usr/local/texlive/2016/bin/x86_64-darwin/pdflatex
ERROR:     !pdf-engine /usr/local/texlive/2016/bin/x86_64-darwin/pdflatex is not compatible with output format html
```

The same happens when I give the same executable path with the panzer command line option `--pdf-engine`. Can you tell what I need to fix here?

On the other point, you're right that many of my options are defaults, but this has been my way of tracking which options I'm assuming are on or off. I can move that to a comment elsewhere. I confirm I can send `—from=(option list)` OK. I think the documentation could be clearer here, as it implied to me that I couldn't use `—from` in a panzer call.

**Comment by msprev** [comment]
Ok, you need to specify it as a 'latex:' writer. It's a long time since I've used the pandoc pdf direct output. You should not be using my panzer styles if you want to use pandoc's pdf direct output. You will need to write you own. Try this:

```
---
title: "test"
style: Test
styledef:
    Test:
        latex:
            metadata:
                geometry:
                  - top=5.5cm
                  - bottom=1.5cm
...

hello world
```

And compile it with `panzer test.md -o test.pdf -t latex`
